FPTJobMatch/Models/JobPost.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FPTJobMatch.Models
{
    public class JobPost
    {
        public int Id { get; set; }
        public string JobName { get; set; }
        public string Description { get; set; }
        public string Industry { get; set; }
        public string RequireSkill { get; set; }
        [Required(ErrorMessage = "Salary is required.")]
        [Range(0, 99999999, ErrorMessage = "Salary must be a positive number and cannot exceed 8 digits.")]
        public int Salary { get; set; }
        public string Image { get; set; }

        public string EmployerId { get; set; }
        public User Employer { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public ICollection<Application> Applications { get; set; }

    }
}

FPTJobMatch/Controllers/JobPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FPTJobMatch.Data;
using FPTJobMatch.Models;

namespace FPTJobMatch.Controllers
{
    public class JobPostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JobPostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: JobPosts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.JobPost.Include(j => j.Category);
            return View(await applicationDbContext.ToListAsync());
        }
        [HttpPost]
        public IActionResult SearchProduct(string keyword)
        {
            var products = _context.JobPost.Where(p => p.JobName .Contains(keyword)).ToList();
            return View("Index", products);
        }

        public IActionResult SortByPriceASC()
        {
            var products = _context.JobPost.OrderBy(p => p.RequireSkill).ToList();
            return View("Index", products);
        }
        public IActionResult SortByPriceDSC()
        {
            var products = _context.JobPost.OrderByDescending(p => p.Salary).ToList();
            return View("Index", products);
        }

        // GET: JobPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobPost = await _context.JobPost
                .Include(j => j.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jobPost == null)
            {
                return NotFound();
            }

            return View(jobPost);
        }

        // GET: JobPosts/Create
        public IActionResult Create()
        {
            ViewData["CategoryName"] = new SelectList(_context.Category, "Id", "CategoryName");
            return View();
        }

        // POST: JobPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,JobName,Description,Industry,RequireSkill,Salary,Image,CategoryName")] JobPost jobPost)
        {
            if (ModelState.IsValid)
            {
                _context.Add(jobPost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryName"] = new SelectList(_context.Category, "Id", "CategoryName", jobPost.CategoryId);
            return View(jobPost);
        }

        // GET: JobPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobPost = await _context.JobPost.FindAsync(id);
            if (jobPost == null)
            {
                return NotFound();
            }
            ViewData["CategoryName"] = new SelectList(_context.Category, "Id", "CategoryName", jobPost.CategoryId);
            return View(jobPost);
        }

        // POST: JobPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,JobName,Description,Industry,RequireSkill,Salary,Image,CategoryId")] JobPost jobPost)
        {
            if (id != jobPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jobPost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobPostExists(jobPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryName"] = new SelectList(_context.Category, "Id", "CategoryName", jobPost.CategoryId);
            return View(jobPost);
        }

        // GET: JobPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobPost = await _context.JobPost
                .Include(j => j.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jobPost == null)
            {
                return NotFound();
            }

            return View(jobPost);
        }

        // POST: JobPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jobPost = await _context.JobPost.FindAsync(id);
            _context.JobPost.Remove(jobPost);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JobPostExists(int id)
        {
            return _context.JobPost.Any(e => e.Id == id);
        }
    }
}

FPTJobMatch/Views/JobPosts/Create.cshtml
@model FPTJobMatch.Models.JobPost

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>JobPost</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="JobName" class="control-label"></label>
                <input asp-for="JobName" class="form-control" />
                <span asp-validation-for="JobName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Industry" class="control-label"></label>
                <input asp-for="Industry" class="form-control" />
                <span asp-validation-for="Industry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequireSkill" class="control-label"></label>
                <input asp-for="RequireSkill" class="form-control" />
                <span asp-validation-for="RequireSkill" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryName"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FPTJobMatch/Views/JobPosts/Delete.cshtml
@model FPTJobMatch.Models.JobPost

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>JobPost</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JobName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JobName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Industry)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Industry)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequireSkill)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequireSkill)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FPTJobMatch/Views/JobPosts/Details.cshtml
@model FPTJobMatch.Models.JobPost

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>JobPost</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JobName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JobName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Industry)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Industry)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequireSkill)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequireSkill)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

FPTJobMatch/Views/JobPosts/Edit.cshtml
@model FPTJobMatch.Models.JobPost

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>JobPost</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="JobName" class="control-label"></label>
                <input asp-for="JobName" class="form-control" />
                <span asp-validation-for="JobName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Industry" class="control-label"></label>
                <input asp-for="Industry" class="form-control" />
                <span asp-validation-for="Industry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequireSkill" class="control-label"></label>
                <input asp-for="RequireSkill" class="form-control" />
                <span asp-validation-for="RequireSkill" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryName"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FPTJobMatch/Views/JobPosts/Index.cshtml
@model IEnumerable<FPTJobMatch.Models.JobPost>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="card-group">
    <h1>Product List</h1>
    <div class="container-fluid"
    <div class="row">
            @*         <div class="col"> search function
           <form method="post" asp-controller="Products" asp-action="SearchProduct">
                <div form="form-group">
                    <input class="form-control" name="keyword" type="search" placeholder="Enter keyword to search" required />
                </div>
            </form> 
        </div>
           <div class="col">
                <form method="post" asp-controller="JobPosts" asp-action="SearchProduct">
             <div form="form-group">
                <input class="form-control" name="keyword" type="search" placeholder="Enter keyword to search" required />
             </div>
                </form>
        </div> *@ 
        <div class="col">
            <a class="btn btn-primary" asp-controller="Products" asp-action="SortByPriceASC">Sort by price ASC</a>
            <a class="btn btn-danger" asp-controller="Products" asp-action="SortByPriceDSC">Sort by price DSC</a>
        </div>
    </div>
    </div>
@foreach (var item in Model) 
{
                <div class="col-md-3 mt-3">
                    <div class="card text-center">
                        <div class="card-body">
                            <a href="@Url.Action("Edit", "JobPosts", new { id = item.Id })"><img src="@item.Image" width="150" height="150" /></a>
                            <h5 class="card-text text-uppercase text-primary">@item.Industry</h5>
                            <p class="card-text text-danger bg-warning">@item.JobName</p>
                            <div class="tag-container">
                                <span class="tag">@item.RequireSkill</span>
                             </div>
                        </div>
                    </div>
                </div>
@*             <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td> *@
    }
</div>